### PR TITLE
fix: set text-area's aria-label as property

### LINKED ISSUE #54: Update _setAriaLabel to use a private property
The `_setAriaLabel` is a protected method but is called by other component
:
https://github.com/vaadin/vaadin-messages/blob/68ffc34935d8bdff84fd098d55b07c46e19a0e8b/src/vaadin-message-input.js#L125

We should consider removing that method and using a property instead, [example](https://github.com/vaadin/vaadin-app-layout/blob/96f249fdd24ecbba8af98e5106d5ce6dc243eefa/src/vaadin-drawer-toggle.js#L79-L84).
The logic of setting the `aria-label` on the input element can be moved to the property observer.

### PR DESCRIPTION
**Pull request by pekam**
fixes #54

### CODE REVIEW

File: src/vaadin-message-input-text-area.js [hunk 1]
```diff
@@ -59,9 +68,9 @@ class MessageInputTextAreaElement extends TextAreaElement {
     });
   }
 
-  _setAriaLabel(message) {
+  __ariaLabelChanged(ariaLabel) {
     // Set aria-label to provide an accessible name for the labelless input
-    this.inputElement.setAttribute('aria-label', message);
+    this.inputElement.setAttribute('aria-label', ariaLabel);
```
Comment (web-padawan) [inline src/vaadin-message-input-text-area.js:73]: This will set `aria-label`  to `undefined` by default. Maybe we could check if `ariaLabel` is truthy.

**Review by web-padawan — APPROVED** [review]
